spring:
  cloud:
    gateway:
      routes:
        - id: add-hello-prefix
          uri: http://localhost:8001
          predicates:
            - Method=GET
          filters:
            - AddGreetingPath=hello,gatewayTest
        - id: add-hola-prefix
          uri: http://localhost:8001
          predicates:
            - Method=GET
          filters:
            - name: AddGreetingPath
              args:
                greeting: hola